{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled .Values.redis.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fleet.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "fleet.fullname" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
{{- end }}
