apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: go-api
  ports:
    - port: {{ .Values.goApi.service.port }}
      targetPort: {{ .Values.goApi.service.targetPort }}
  type: ClusterIP