apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ include "fleet.fullname" . }}
spec:
  selector:
    app: go-api
  ports:
    - name: http
      port: {{ .Values.goApi.service.port }}
      targetPort: {{ .Values.goApi.service.targetPort }}
  type: ClusterIP