{{- if .Values.externalSecrets.enabled -}}
# ClusterSecretStore connects to Vault
# This is created once per cluster and shared across namespaces
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: {{ .Values.externalSecrets.vault.path | quote }}
      version: {{ .Values.externalSecrets.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.externalSecrets.vault.tokenSecretName | quote }}
          key: "token"
          namespace: {{ .Values.externalSecrets.vault.tokenSecretNamespace | quote }}
{{- end }}
