{{- if .Values.worker.enabled -}}
{{- $fullName := include "investify.fullname" . -}}
{{- $namespace := include "investify.namespace" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-worker
  namespace: {{ $namespace }}
  labels:
    {{- include "investify.labels" . | nindent 4 }}
    app: {{ $fullName }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ $fullName }}-worker
  template:
    metadata:
      labels:
        {{- include "investify.labels" . | nindent 8 }}
        app: {{ $fullName }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.php.repository }}:{{ .Values.image.php.tag }}"
          imagePullPolicy: {{ .Values.image.php.pullPolicy }}
          command: {{ toYaml .Values.worker.command | nindent 12 }}
          env:
            {{- range $key, $value := .Values.laravel.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: "{{ $fullName }}-redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.port }}"
            {{- end }}
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-connection
                  optional: true
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-host
                  optional: true
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-port
                  optional: true
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-database
                  optional: true
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-username
                  optional: true
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: db-password
                  optional: true
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: app-key
                  optional: true
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: database-url
                  optional: true
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
