{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "investify.fullname" . }}-redis
  namespace: {{ include "investify.namespace" . }}
  labels:
    {{- include "investify.labels" . | nindent 4 }}
    app: {{ include "investify.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "investify.fullname" . }}-redis
  template:
    metadata:
      labels:
        {{- include "investify.labels" . | nindent 8 }}
        app: {{ include "investify.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "investify.fullname" . }}-redis
  namespace: {{ include "investify.namespace" . }}
  labels:
    {{- include "investify.labels" . | nindent 4 }}
    app: {{ include "investify.fullname" . }}-redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    app: {{ include "investify.fullname" . }}-redis
{{- end }}
