{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "investify.fullname" . }}-api
  namespace: {{ include "investify.namespace" . }}
  labels:
    {{- include "investify.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "investify.fullname" . }}-api
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.monitoring.serviceMonitor.path }}
  namespaceSelector:
    matchNames:
      - {{ include "investify.namespace" . }}
{{- end }}
