apiVersion: v1
kind: Service
metadata:
  name: {{ include "investify.fullname" . }}-app
  namespace: {{ include "investify.namespace" . }}
  labels:
    {{- include "investify.labels" . | nindent 4 }}
    app: {{ include "investify.fullname" . }}-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "investify.fullname" . }}-app
